title: Pruek CV
logo: /assets/img/pruek-circle.png
description: |
  My name is Arniwatt Chonkiattipoom or call me Pruek.
  I'm looking for ......
  Stay safe from COVID-19
theme: jekyll-theme-minimal
