title: <a href="https://github.com/pruekk">pruekk</a>
logo: /assets/images/pruek-circle.png
description: |
    <a href="https://pruekk.github.io/pruekk/#arniwatt-chonkiattipoom">/me</a><br>
    <a href="https://pruekk.github.io/pruekk/#skills">/skills</a><br>
    <a href="https://pruekk.github.io/pruekk/#work-experience">/work-experience</a><br>
    &ensp;- <a href="https://pruekk.github.io/pruekk/#exxonmobil-bangkok-thailand">/exxonmobil</a><br>
    &ensp;- <a href="https://pruekk.github.io/pruekk/#refinitiv-bangkok-thailand">/refinitiv</a><br>
    <a href="https://pruekk.github.io/pruekk/#leadership-and-projects">/leadership-and-projects</a><br>
    <a href="https://pruekk.github.io/pruekk/#education">/education</a><br>
theme: jekyll-theme-minimal
