title: null
logo: /assets/images/pruek-circle.png
description: |
    Hi everyone, I'm _**Pruek**_.<br>
    Right now, I having fun with **DevOps** path to make the system or application more reliable and automatic however I'm looking for new **challenges** and **opputunities**.<br>
    I'm kindly an introvert person but once you get to know me more, I would describe my personality as **friendly**, **funny** and **easy going**.<br>
    <hr>
    [SKILLS](#skills)
    [WORK EXPERIENCE](#work-experience)
    [LEADERSHIP AND PROJECTS](#leadership-and-projects)
    [EDUCATION](#education)
theme: jekyll-theme-minimal
