title: Pruek CV
logo: /assets/img/pruek-circle.png
description: |
  My name is Arniwatt Chonkiattipoom or call me Pruek.<br/>
  I'm looking for ......<br/>
  Stay safe from COVID-19
theme: jekyll-theme-minimal
