title: Pruek CV
logo: /assets/img/pruek-circle.png
description: |-\n
  My name is Arniwatt Chonkiattipoom or call me Pruek.\n
  I'm looking for ......\n
  Stay safe from COVID-19
theme: jekyll-theme-minimal
